# Generated by Django 3.2.3 on 2021-05-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_apps', '0002_category_meson_product_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meson',
            name='event_start',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
