# Generated by Django 3.2.3 on 2021-05-17 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_apps', '0003_alter_meson_event_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meson',
            name='event_start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
