# Generated by Django 3.2.3 on 2021-05-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_apps', '0009_auto_20210525_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meson',
            name='event_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
