# Generated by Django 3.1.1 on 2021-06-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_apps', '0010_alter_meson_event_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='name', upload_to='products'),
        ),
    ]
