# Generated by Django 3.1.1 on 2021-06-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_apps', '0011_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='products'),
        ),
    ]
